export interface CreateBooking{ 
    booking_no:string,
    pickup:string,
    dropoff:string,
    passenger:string,
    date:string,
    time:string,
    return_date:string,
    return_time:string,
    estimated_trip_time:string,
    distance:string,
    currency:string,
    vehicle_name:string,
    passengers_no:string,
    medium_bags:string,
    passenger_name:string,
    passenger_email:string,
    passenger_contact_no:string,
    plane_arriving_form: string,
    airline_name: string,
    flight_number: string,
    cruise_ship_name: string,
    train_arriving_from: string,
    train_name: string,
    train_operator:string,
    hotel_name:string,
    pickup_address:string,
    destination_name: string,
    destination_address: string,
    agentforeign:number
}

